spring:
  application:
    name: licensingservice
  config:
    import: "optional:configserver:"
  profiles:
    active: dev
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: SpringBootKeycloak
  ssl-required: external
  resource: licensing-service
  credentials:
    secret: PanoVH9OseMJKCGGiMMMnGdVQpz219Me
  bearer-only: true
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/