spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: loan
          uri: lb://loan/loan
          predicates:
            - Path=/loan/**
#  security:
#    oauth2:
#      client:
#        provider:
#          my-keycloak-provider:
#            issuer-uri: http://localhost:8080/realms/bank
#            token-uri: http://localhost:8080/realms/bank/protocol/openid-connect/token
#            authorization-uri: http://localhost:8080/realms/bank/protocol/openid-connect/auth
#            user-info-uri: http://localhost:8080/realms/bank/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username
#        registration:
#          keycloak-spring-gateway-client:
#            provider: my-keycloak-provider
#            scope: openid
#            client-id: gateway
#            client-secret: PFH6ByjlVRr6V3T7q5oG9ySLNW6ktmGE
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank
            token-uri: http://localhost:8080/realms/bank/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/realms/bank/protocol/openid-connect/auth
            user-info-uri: http://localhost:8080/realms/bank/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          bank-gateway:
            provider: keycloak
            scope:
              - openid
            client-id: gateway
            client-secret: PFH6ByjlVRr6V3T7q5oG9ySLNW6ktmGE
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

server:
  port: 8072
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/