spring:
  application:
    name: loan
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/bank/protocol/openid-connect/certs
#          both is correct
#          jwk-set-uri: http://localhost:8080/realms/bank/protocol/openid-connect/certs
#          issuer-uri: http://localhost:8080/realms/bank
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/