server:
  port: 8888
spring:
  profiles:
    active: native,git
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/Projects/microservice/config-server/src/main/resources/config
        git:
          uri: https://github.com/Mojtaba98mz/microservices-config.git
          clone-on-start: true
          default-label: master
encrypt:
  keystore:
    location: classpath:key/microservice.jks
    password: 1qaz!QAZ
    alias: microservice