server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/Projects/config-server/src/main/resources/config/licensingservice
encrypt:
  keystore:
    location: classpath:key/microservice.jks
    password: 1qaz!QAZ
    alias: microservice